name: Notification Push avec Analyse de Code

on: 
  push: 
    branches: 
      - '*'

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: |
          npm install

      - name: Exécuter le script d'envoi d'e-mail
        run: |
          node sendMail.js