name: Notification Push avec Analyse de Code

on: 
  push: 
    branches: 
      - '*'

jobs:
  analyze-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Obtenir l'email de l'auteur du commit
        id: get_email
        run: |
          userEmail=$(git log -1 --pretty=format:'%ae')
          if [[ ! "$userEmail" == *@gmail.com ]]; then
            userEmail="${userEmail%@*}@gmail.com"
          fi
          echo "userEmail=$userEmail" >> $GITHUB_ENV

      - name: Analyser le code
        id: analyze_code
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
              code=$(git diff HEAD~1 HEAD)
              improved_code=$(node analyze.js "$code") # Appeler votre script d'analyse
              echo "improved_code=$improved_code" >> $GITHUB_ENV
          else
              echo "Pas assez de commits pour analyser."
              echo "improved_code=aucun changement" >> $GITHUB_ENV
          fi

      - name: Envoyer une notification par email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: 'fops415@gmail.com'
          password: 'wzrq uhqj iekx irpn'
          subject: 'Push réussi avec analyse de code'
          body: |
            Le push sur la branche ${{ github.ref }} a été effectué avec succès !
            Suggestions d'amélioration du code :
            ${{ env.improved_code }}
          to: ${{ env.userEmail }}
          from: 'fops415@gmail.com' # Remplacez par votre adresse e-mail